#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Hikaru Maeda
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    ans += tonum(line)

print(ans)
#print(ans, end = " ")

#if ans != 0:
    #if ans%2 == 0:
        #print("答えは偶数です")
    #else:
        #print("答えは奇数です")
